### ISSUE TITLE
Missing run/decaykiller.cc and run/pdgreader.cc

### ISSUE THREAD

**Issue by chunshen1987** [steinhor/best_sampler#5]
Hi,

I am trying to compile the sampler. I got the following errors during the CMake stage,

CMake Error at CMakeLists.txt:19 (add_executable):
  Cannot find source file:

    run/decaykiller.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at CMakeLists.txt:18 (add_executable):
  Cannot find source file:

    run/pdgreader.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at CMakeLists.txt:19 (add_executable):
  No SOURCES given to target: decaykiller

CMake Error at CMakeLists.txt:18 (add_executable):
  No SOURCES given to target: pdgreader

**Comment by doliinychenko** [comment]
I have fixed the cmake machinery. Could you check, if it works for you?
